gui:
  theme:
    activeBorderColor:
      - cyan
    inactiveBorderColor:
      - default
    optionsTextColor:
      - default
    selectedLineBgColor:
      - cyan
    cherryPickedCommitBgColor:
      - default
    cherryPickedCommitFgColor:
      - default
    unstagedChangesColor:
      - default
    defaultFgColor:
      - default
    searchingActiveBorderColor:
      - default
    authorColors:
      '*': default
