[general]
# import = ["~/.config/alacritty/themes/themes/night_owlish_light.toml"]
import = ["~/.config/alacritty/themes/themes/night_owl.toml"]

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
# opacity = 0.85
# blur = true
dimensions = { columns = 150, lines = 45 }
startup_mode = "Maximized"

[font]
normal = { family = "Jetbrains Mono", style = "Light" }
bold = {style = "Medium" }
italic = { style = "ThinItalic" }
bold_italic = {style = "MediumItalic" }
size = 14

[bell]
animation = "Ease"
duration = 400

[cursor]
style = { blinking = "Always" }

